#!/bin/bash

USERNAME="LewisMagangi"
NEW_PAT="Personal Access Token"  # Replace with your new Personal Access Token

# Repositories to exclude from cloning
EXCLUDE_REPOS=(
    "cs-video-courses" 
    "Summer2025-Internships" 
    "tech-jobs-with-relocation" 
    "Dynamic_Cryptosuite" 
    "skills-code-with-codespaces" 
    "Hash" 
    "escrow" 
    "data-leaks" 
    "ssh" 
    "Networks" 
    "Datacamp-Python-Programmer" 
    "micropilot-entry-challenge" 
    "ML-For-Beginners" 
    "AI-For-Beginners" 
    "the-book-of-secret-knowledge" 
    "The-Complete-FAANG-Preparation" 
    "Projects" 
    "mltype" 
    "interview"
)

# Check if the script is running as root
if [ "$(id -u)" != "0" ]; then
    echo "WARNING: This script should only be run in a secure environment, such as a root environment, to ensure that the Personal Access Token (PAT) is not accessible to unauthorized individuals."
    exit 1
fi

# Get the list of repositories for the user
REPOS=$(curl -s -H "Authorization: token $NEW_PAT" "https://api.github.com/users/$USERNAME/repos" | grep -o 'clone_url": "https://[^"]*' | sed 's/clone_url": "//')

# Loop through the list and clone each repository
for REPO_URL in $REPOS; do
    REPO_NAME=$(basename "$REPO_URL" .git)
    
    # Check if the repository is in the exclude list
    if [[ " ${EXCLUDE_REPOS[@]} " =~ " ${REPO_NAME} " ]]; then
        echo "Skipping $REPO_NAME"
        continue
    fi

    # Clone the repository with the new PAT included in the URL
    git clone "https://$NEW_PAT@github.com/$USERNAME/$REPO_NAME.git"
done

